namespace MyNihongo.Mockurai.Utils;

internal static class NamedTypeSymbolEx
{
	public static INamedTypeSymbol? TryGetBaseClassWithFunctionName(this INamedTypeSymbol @this, string functionName)
	{
		var baseType = @this.BaseType;

		while (baseType is not null)
		{
			// Generated by source generators
			var hasAttribute = baseType.GetAttributes()
				.Any(static x => x.AttributeClass?.Name == MockGeneratorConst.GenerateAttributeName);

			if (hasAttribute)
				return baseType;

			// In case the method has been added manually
			var hasMethod = baseType.GetMembers(functionName)
				.OfType<IMethodSymbol>()
				.Where(static x => x.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected)
				.Any();

			if (hasMethod)
				return baseType;

			baseType = baseType.BaseType;
		}

		return null;
	}
}
