namespace MyNihongo.Mockurai.Utils;

internal static class NamedTypeSymbolEx
{
	extension(INamedTypeSymbol @this)
	{
		public INamedTypeSymbol? TryGetBaseClassWithFunctionName(string functionName)
		{
			var baseType = @this.BaseType;

			while (baseType is not null)
			{
				// Generated by source generators
				var hasAttribute = baseType.HasGenerateAttribute();

				if (hasAttribute)
					return baseType;

				// In case the method has been added manually
				var hasMethod = baseType.GetMembers(functionName)
					.OfType<IMethodSymbol>()
					.Where(static x => x.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected)
					.Any();

				if (hasMethod)
					return baseType;

				baseType = baseType.BaseType;
			}

			return null;
		}

		public INamedTypeSymbol? TryGetBaseClassWithNestedClassName(string className)
		{
			var baseType = @this.BaseType;

			while (baseType is not null)
			{
				// Generated by source generators
				var hasAttribute = baseType.HasGenerateAttribute();

				if (hasAttribute)
					return baseType;

				// In case the method has been added manually
				var hasMethod = baseType.GetTypeMembers(className)
					.Where(static x => x.TypeKind == TypeKind.Class)
					.Where(static x => x.DeclaredAccessibility is Accessibility.Public or Accessibility.Protected)
					.Any();

				if (hasMethod)
					return baseType;

				baseType = baseType.BaseType;
			}

			return null;
		}
	}

	extension(INamedTypeSymbol @this)
	{
		private bool HasGenerateAttribute()
		{
			return @this
				.GetAttributes()
				.Any(static x => x.AttributeClass?.Name is MockGeneratorConst.GenerateAttribute or MockGeneratorConst.GenerateAttributeName);
		}
	}
}
